project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference
    right:
      - icon: github
        href: https://github.com/edgararuiz/chattr-python
quartodoc:
  package: chattr
  options: null
  dir: 'docs/reference'
  sections:
    - title: Main functions
      contents: 
        - chat
        - app
    - title: Utils
      contents:
        - use
        - _defaults
