project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
  
website:
  title: chapy
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference
    right:
      - icon: github
        href: https://github.com/edgararuiz/chapy

quartodoc:
  package: chapy
  options: null
  style: pkgdown
  dir: reference
  out_index: _api_index.qmd
  dynamic: true
  sections:
    - title: Main functions
      contents: 
        - chat
        - app
    - title: Utils
      contents:
        - use
        - session_defaults
