[project]
name = "chattr"
version = "0.0.2"
authors = [
  { name="Edgar Ruiz", email="edgararuiz@gmail.com" },
]
description = "Enables interaction with different LLMs via the console and Shiny app"
readme = "README.md"
requires-python = ">=3.8"
