default:
  provider: Ollama
  model: llama3.1
  path: http://localhost:11434/
  label:  Ollama
  include_history: TRUE
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: FALSE
  system_msg: You are a helpful coding assistant that uses Python to analyze data. Keep coments brief
